### ISSUE TITLE
Using extension on youtube main page results with "undefined".

### ISSUE THREAD

**Issue by GrzegorzDrozd** [igorlogius/handleWith#3]
Hi,

When using this extension on youtube main page on a video link results with undefined url. 
Using standard handleWith.sh with branch added for VLC:

```#!/bin/bash 

str=$1
act=$(echo $1 | sed 's/:\/\/.*//')
url=$(echo $1 | sed 's/^[^:\/\/]*:\/\///')

echo "act= $act, url= $url" 
echo "act= $act, url= $url" >> /tmp/handleWith.log

case $act in  
    "youtube-dl" )
	echo "action $act executed " >> /tmp/handleWith.log
	/usr/bin/youtube-dl  "$url"
	;;
    "vlc" )
	echo "action $act executed " >> /tmp/handleWith.log
	/usr/bin/vlc --playlist-enqueue "$url"
	;;
    *)
	echo "$1" >> /tmp/handleWith.log
	;;
esac
```
That results with logs:

```
action vlc executed 
act= vlc, url= undefined
action vlc executed 
act= vlc, url= undefined
action vlc executed 
```

I think it got broken quite recently.

**Comment by igorlogius** [comment]
I'll check.

**Comment by igorlogius** [comment]
It seems last try on an improvement ... was the culpit.
I tried to rely on firefoxes build in mechanism to detect  anchor's ... which in the case of youtube ... doenst work, since the actual "clickable" element isnt an anchor file but a div with some javascript, which evokes the redirect.

It only worked before because i had a method in place searched for the nearest anchor element ... which luckly hasnet been complety removed by yotubue yet.

I'll re-add the anchor search function ... that should bix the issue.

**Comment by igorlogius** [comment]
Version 1.1.5 is released and should fix the issue.
Sorry again for the trouble.

**Comment by GrzegorzDrozd** [comment]
Confirming it is fixed now :) Thanks :)

ps: trying to promote your extension among my friends because it AWESOME :)

**Comment by igorlogius** [comment]
> Confirming it is fixed now :) Thanks :)

That's good to hear, 
since i am only testing it on my own setup i am always a little worried that i might miss something.
So thank your for the confirmation.  

> ps: trying to promote your extension among my friends because it AWESOME :)

Glad that you think it can be useful for others too, 
just dont annoy them too much ;)
